// <auto-generated />
namespace BarraFisik.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_MovimentacaoEstoque_Estoque : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_MovimentacaoEstoque_Estoque));
        
        string IMigrationMetadata.Id
        {
            get { return "201602181225337_Update_MovimentacaoEstoque_Estoque"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
