// <auto-generated />
namespace BarraFisik.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_ProdutosCategoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_ProdutosCategoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201602121732288_Add_ProdutosCategoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
