// <auto-generated />
namespace BarraFisik.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_isAtivo_Funcionarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_isAtivo_Funcionarios));
        
        string IMigrationMetadata.Id
        {
            get { return "201601231621399_Add_isAtivo_Funcionarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
